export const allItems =  [
    { _id: 1, title: 'Automotive' },
    { _id: 2, title: 'Baby' },
    { _id: 3, title: 'Beauty & Personal Care' },
    { _id: 4, title: 'Books' },
    { _id: 5, title: 'Boys Fashion' },
    { _id: 6, title: 'Computers' },
    { _id: 7, title: 'Deals' },
    { _id: 8, title: 'Digital Music' },
    { _id: 9, title: 'Electronics' },
    { _id: 10, title: 'Girls Fashion' },
    { _id: 11, title: 'Health and Household' },
    { _id: 12, title: 'Home & Kitchen' },
    { _id: 13, title: 'Industrial & Scientific' },
    { _id: 14, title: 'Kindle Store' },
    { _id: 15, title: 'Luggage' },
    { _id: 16, title: 'Mens Fashion' },
    { _id: 17, title: 'Movies & TV ' },
    { _id: 18, title: 'Music, CDs & Vinyl' },
    { _id: 19, title: 'Pet Supplies' },
    { _id: 20, title: 'Prime Video' },
    { _id: 21, title: 'Software' },
    { _id: 22, title: 'Sports & Outdoors' },
    { _id: 23, title: 'Tools & Home Improvement' },
    { _id: 24, title: 'Toys & Games' },
    { _id: 25, title: 'Video Games' },
    { _id: 26, title: 'Womens Fashion' },
  ]